### ISSUE TITLE
Documentation on authentication 

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-mobile-apps-cordova-client#1]
I'm trying to find documentation on how to connect to a push service which is authenticated using Azure AD authentication. I have the code in place but when I view the communication between client and server I can see Azure is redirecting the requests to a login page. For API and SignalR calls I'm using Bearer authentication so I have that token, just no clue on where I can set it. Please update the documentation on this (or point me to the link I've been overlooking).

**Comment by jsiegmund** [comment]
Ok so I've got it working in the meantime. For SignalR you can reuse the X-ZUMO-AUTH and X-ZUMO-VERSION headers to provide header authentication for your requests. In short:

`var token = mobileServiceClient.currentUser.mobileServiceAuthenticationToken;
var version = mobileServiceClient.version;

var headers = {
    "X-ZUMO-AUTH": token,
    "X-ZUMO-VERSION": version
};
$.signalR.ajaxDefaults.headers = headers;`

Maybe I can misuse this issue for another question. I'm wondering what the best way is to check whether my user is logged in or not. currentuser == null seems easy enough but I'm not entirely sure whether that's 100% correct. I want to prevent the login screen from popping up unnecessarily, but I also want to make sure the auth token gets refreshed  to prevent being logged out.

**Comment by adrianhall** [comment]
Something like this:

```
function loggedIn(client) {
    // If token doesn't exist, we aren't authenticated
    if (client.currentUser === null) return false;
    
    // Verify expiry time
    var token = client.currentUser.mobileServiceAuthenticationToken;
    var decoded = jwt.decode(token);
    if (typeof decoded.payload.exp !== 'undefined') {
        // exp is a UNIX Timestamp
        var ts = Math.round((new Date()).getTime() / 1000);
        if (ts > decoded.payload.exp) return false;
    }
    
    // If there isn't an expiry or we haven't expired, we are authenticated
    return true; 
}
```

If the user has been logged in, then the JWT token expiry must be checked.  I haven't checked this code, but it's close.

**Comment by jsiegmund** [comment]
Thanks a lot!
