### ISSUE TITLE
Android 6 client can no longer register for push notifications

### ISSUE THREAD

**Issue by atsats** [Azure/azure-mobile-apps-cordova-client#12]
I have a Cordova app using this plugin. It was working fine for a number of weeks and the same software for registering for push notifications is currently working fine on Windows UWP, iOS and Android 5. 

Starting this week, the device running Android 6 is no longer able to register for push notifications. It does not receive an error back from the 
`client.push.register(...)`
The call succeeds and a seemingly valid PNS handle is returned - but this registration never shows up in the Azure Notification Hub list of devices.

I've tried everything from rekeying the Google API to completely deleting the notification hub and re-adding in Azure. After all these changes, the Android 6 device is still not able to register.

I have 2 questions: 
a) Are there any breaking changes that could be affecting Android 6 device registrations?
b) Can I completely bypass the plugin and do the registration on the server side? [ I tried this unsuccessfully so far, but the available documentation on this  is so poor and I'm hoping you can point me to a working example from a Cordova client.]

**Comment by shrishrirang** [comment]
Is this bug same as https://github.com/Azure/azure-mobile-apps-cordova-client/issues/11? The workaround mentioned in https://github.com/Azure/azure-mobile-apps-cordova-client/issues/11 should be able to get you unblocked quickly.

**Comment by atsats** [comment]
Unfortunately this is separate. The Android 6 device is still not connecting after I reverted to the old plugin version. I'm still investigating on my side what the cause could be.

**Comment by shrishrirang** [comment]
The issue you mentioned in #11 and this issue look related to me. There is a push related bug that was introduced inadvertently. What is the plugin version you are now using? The latest version in npm should work fine. Can you give that a try: `cordova plugin add cordova-plugin-ms-azure-mobile-apps`.

**Comment by atsats** [comment]
Just tried removing and then re-adding the plugin from the CLI as you suggested, but the device is still unable to connect.

**Comment by atsats** [comment]
I'm able to reproduce this at will now and opened an associated issue: [#805](https://github.com/phonegap/phonegap-plugin-push/issues/805)

**Comment by atsats** [comment]
I'm able to reproduce this at will now and I have a work around. It actually has nothing to do with the  `cordova-plugin-ms-azure-mobile-apps` I opened an associated issue: [#805](https://github.com/phonegap/phonegap-plugin-push/issues/805)
