### ISSUE TITLE
Optionally hide the window when authentication is being processed.

### ISSUE THREAD

**Issue by ErkoKnoll** [Azure/azure-mobile-apps-cordova-client#17]
Hi,

By looking at the Cordova InAppBrowser documentation they provide an option to hide the window (hidden attribute) and "show" method which probably brings the window to foreground. I haven't tested if it works as I suspect.

Idea here is to not display loading indicator while logging in and only show the in app browser window when refresh token is no longer valid and user needs to re-enter their credentials because performing authentication on app startup takes at least 2 seconds and blocks the rest of the activity. From user experience point of view it is something that could be improved. However it should be optional and configurable since most of the apps actually need authentication to be completed before proceeding to main page but some apps that make use of offline data could show data that is locally stored and have the authentication performed in the background and only prompt the window when credentials are required.

**Comment by adrianhall** [comment]
Hi Erko,

This is completely doable without any enhancements.  You need to follow the standard "client-flow" mechanism.  Blog for this is here:  https://shellmonger.com/2016/04/06/30-days-of-zumo-v2-azure-mobile-apps-day-4-adal-integration/
