### ISSUE TITLE
Expand related entities not work.

### ISSUE THREAD

**Issue by PeaceDeveloper** [Azure/azure-mobile-apps-cordova-client#18]
I am using cordova-plugin-ms-azure-mobile-apps 2.0.0-beta4.
Below the code block that I am using to query a table, but with a option to expand specialties. But not work.

 var client = new WindowsAzure.MobileServiceClient(API_ENDPOINT.url);
                var specialtyTable =
                    client.getTable('service');
                // Execute a query for uncompleted items and process
                specialtyTable
                    .where({ id: service.id })     // Set up the query
                    //.select('name, specialties')
                    .read({ 'expand': 'Specialties' })                         // Read the results
                    .then(createItem, handleError);

**Comment by adrianhall** [comment]
What does not work about it?  If handleError is called, what is the error.  Is it failing at the backend?  If so, what do the logs look like?   Do you have an ASP.NET or Node (EasyTables) backend?  What is your backend definitions look like?

**Comment by PeaceDeveloper** [comment]
So, not an error is returned for me, only not take de table related on expand parameter. Have I to do something in my backend asp.net c#? Thanks for reply.

**Comment by adrianhall** [comment]
Yeah - the client does not support $expand natively.
