### ISSUE TITLE
Cordova 6.2.0 breaks table connections with beta5 

### ISSUE THREAD

**Issue by markau** [Azure/azure-mobile-apps-cordova-client#24]
I don't know if there is a recommended version of Cordova but just letting you know 6.2.0 doesn't work with the beta5 client.

I was setting up a development laptop and found that connections to a table (e.g. `table.insert()`', or a `push()` in a syncContext, give error "Unexpected connection failure".  There is no attempted connection visible in Fidder. 

I downgraded to Cordova 6.0 and the problem went away.

**Comment by shrishrirang** [comment]
I verified with 6.2.0 and did not see any issues. Can you try again? It is possible you ran into some genuine connection failure when you tried earlier.

**Comment by markau** [comment]
Confirmed working with 6.2.0. 

It could have been networking issues, or a hundred other variables like something I did wrong 😀
