### ISSUE TITLE
Cordova SDK for App Services?

### ISSUE THREAD

**Issue by johnlee** [Azure/azure-mobile-apps-cordova-client#25]
With the move of Azure Mobile Apps to App Services, is there a SDK for Cordova to communicate with App Services? I have a WebAPI2 deployed on App Services and it doesnt seem this mobile apps service is compatible with it.

**Comment by shrishrirang** [comment]
You can use the https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps plugin to connect to the _Azure Mobile Apps_ backend (which is part of _Azure Mobile Apps_). You can refer https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-dotnet-backend-how-to-use-server-sdk/ to be sure you have setup the backend service correctly.

For general reading about _Azure Mobile Apps_ and to understand how that differs from _Azure Mobile Services_ you can refer https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop/ and https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop-migration-from-mobile-services/
