### ISSUE TITLE
unauthorized error in ios while registering for push with azure

### ISSUE THREAD

**Issue by praveens96** [Azure/azure-mobile-apps-cordova-client#26]
getting unauthorized message when trying to do: 
cleint.push.register("apns",...)

here is my code:
var push = PushNotification.init({
android:{
senderID:"927016678125"
},
ios:{
alert:"true",
badge:"true",
sound:"true"
},
windows:{}
});
push.on('registration',function(data){
var appUrl="https://XXXXXXXXXXXXXX/XXXXXX";
// var appUrl="http://xcdxcxc";
var handle = data.registrationId;
var appKey = 
var shareaccKey="wFS90sdfsdfgsdgsdfhfn9+ix7Rwl2SBmdZ2s14VY=";
alert("registered");
console.log("registered:"+data.registrationId);
alert("registered:"+data.registrationId);
//register with plugin
var client =new WindowsAzure.MobileServiceClient(appUrl,shareaccKey);

                      alert(client.push);

                      //alert(client.push.register);
                      client.push.register("apns",data.registrationId).then(function(data1){
                                                                            alert("success azure reg"+data1);

                                                                            },function(err){
                                                                            alert("error in azure reg"+err+err.message);
                                                                            });
in client.push.register it is going to error block and saying Unauthorized.

i am using a sandbox certificate as i am in development and followed: https://azure.microsoft.com/en-in/documentation/articles/app-service-mobile-cordova-get-started-push/ for developing the push piece.

any idea where i am doing wrong?

**Comment by adrianhall** [comment]
- What version of the Cordova plugin are you using?
- Why are you using the API Key?  That's a Mobile Services thing and not a Mobile Apps thing.
- What does your URL look like?  (it's ok to xxx out the sitename, but I need to understand the format)

Thanks,

**Comment by praveens96** [comment]
1. Cordova -v : 6.2.0
2. In this line: 
var client =new WindowsAzure.MobileServiceClient(appUrl,shareaccKey);
i havent used, i was trying different things, i have used the api key also.
3. url format: https://xxxxx.servicebus.windows.net/xxxxx

**Comment by adrianhall** [comment]
So, you have a bunch of issues here.  Firstly, you don't need the shared access key.  

The more serious error, though, is that you are confused about the URL.  You need to generate an Azure Mobile Apps backend to use push registration - the URL is of the format https://xxx.azurewebsites.net - ServiceBus URLs are a variety of things, most notably the notification hub endpoint.  This is not a registration endpoint.

I suggest you start from the basic tutorial and work your way up to Push Notifications - this will generate the proper backend for you.  For the beginning of the tutorial, check https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-cordova-get-started/

**Comment by praveens96** [comment]
Sure @adrianhall , i have done with backend also, but will try once and update you.

**Comment by praveens96** [comment]
@adrianhall i have gone through the above link. i guess that is not what i am looking for. i just wanted to use it for push notifications alone. do i need to provision a database and a cordova app and then use that? i do have an app which is already built. i wanted to add push notifications to it. is there any other better way to do it? could you please suggest?

**Comment by praveens96** [comment]
getting the below error when used the below code:
var appUrl = "http://xxxxxxxxx.azurewebsites.net";
	var client = new WindowsAzure.MobileServiceClient(appUrl);
	alert("push:"+PushNotification+"client:"+client);
	var push = PushNotification.init({
    android: {
        senderID: "927016678125"
    },
    ios: {
        alert: "true",
        badge: true,
        sound: 'false'
    },
    windows: {}
	});
	push.on('registration', function(data) {
		alert("registered:"+data.registrationId);
		var handle = data.registrationId;
		console.log(data.registrationId);
		client.push.register('gcm', handle,function(data){
			alert("data ret client reg:"+data); //got the error in screenshot here.
		}); //, { mytemplate: { body: { data: { message: "{$(messageParam)}" } } }}
		}
	);
	push.on('error', function(e) {
		alert("push errr"+e.message);
		console.log(e.message);
		
	});
	push.on('notification', function (data, d2) {
	  alert('Push Received: ' + data.message);
	});

![screenshot_2016-07-17-14-51-51](https://cloud.githubusercontent.com/assets/8864727/16899795/2f7d4ea2-4c2e-11e6-92ce-664bdbf461c9.png)


Could please let me know where i am doing it wrong?

**Comment by adrianhall** [comment]
Firstly, you need *SOMETHING* on the backend to register clients and deal with the housekeeping.  Azure Mobile Apps is a consolidated backend for which that is one function.   However, it's certainly not the only way to do it.  If you are ONLY doing push registrations, then don't create a table and don't do authentication.  Just do the push registration.  However, you still need to have properly created a mobile apps backend and linked it to a notification hub.

The error indicates that this has not been done properly.  Further than that, it indicates that you have not linked the Notification Hub to the Mobile App backend.  In short, you have not followed the tutorial.

Once you have followed the tutorial and you understand the process, you can certainly modify another app to use the same techniques.  Isolating the technique (in this case, push registration and lifecycle) in a smaller app is a good way to learn about the technology.

**Comment by praveens96** [comment]
@adrianhall update: now i am able to send push notifications to both iOS & android. the mistake is or the step i have skipped thinking xcode will do that is: creating of the provisioning profile. xcode takes care of provisioning profiles in normal cases i.e. for running app in a mobile. i thought it will create the profile as required/as per appID. after week'e time trying out all the things i did step by step and this time i created a provisioning profile and it worked fine :+1: .
the above all errors are because of various things i was trying as part of debugging. 

for future searchers: here is the best link for this: https://azure.microsoft.com/en-in/documentation/articles/app-service-mobile-cordova-get-started-push/ 

and sample code to register:
var GCM_SENDER_ID = 'xxxxxxxxxxxxxxxx'; // Replace with your own ID.
            var mobileServiceClient;
            var pushNotification;

            mobileServiceClient = new WindowsAzure.MobileServiceClient(
                "https://xxxxxxxxxxxxxxxxx.azurewebsites.net/");

            pushNotification = PushNotification.init({
                "android": { senderID: GCM_SENDER_ID, forceShow: "false" },
                "ios": { alert: "true", badge: "true", sound: "true" }
            });


            pushNotification.on('registration', function(data) {

                var handle = data.registrationId;

                // Set the device-specific message template.
                if (isAndroid()) {
                    // Template registration.
                    var template = '{ "data" : {"message":"$(message)"}}';

                    // Register for notifications.
                    mobileServiceClient.push.gcm.registerTemplate(handle,
                        'myTemplate', template, [vm.username])
                        .done(registrationSuccess, registrationFailure);
                } else if (isIOS()) {
                    // Template registration.
                    var template = '{"aps": {"alert": "$(message)","badge":"#(badge)" }}';

                    // Register for notifications.            
                    mobileServiceClient.push.apns.registerTemplate(handle,
                        'myTemplate', template, [vm.username])
                        .done(registrationSuccess, registrationFailure);
                }

                function isIOS() {
                    return (ionic.Platform.device().platform.match(/ios/i))
                }

                function isAndroid() {
                    return (ionic.Platform.device().platform.match(/android/i))
                }

Note:
-------
1. you need to create a azure mobile app in azure portal. (for register in our case)
2.you need to install 2 cordova plugins cordova-plugin-push and cordova-plugin-ms-azure-mobile-apps.
rest is clearly there in the above link.

for testing you can use test send in notification hub (not the mobile app) and for prod you can create a service and call that. @adrianhall are there any default services provided by azure for sending push notifications? like if i send my app id and message it will send messages? Thanks for your help.

**Comment by adrianhall** [comment]
Thanks for confirming @praveens96.  We are working on something that will provide a default registration experience within Azure App Service.  You will still need an App Service, but you won't need any code.  I'm going to blog on the app service team blog once we have it available.

**Comment by kinoli** [comment]
Hi, can you tell me where I can find "https://xxxxxxxxxxxxxxxxx.azurewebsites.net/" value? Is it found in the Azure portal somewhere?

**Comment by praveens96** [comment]
@kinoli you need to create one azure AppService it URL is the above one. its not part of notificationhub

**Comment by adrianhall** [comment]
Hi @kinoli.  Follow the tutorials on the Azure Portal and you will create one as part of the tutorial.

**Comment by adrianhall** [comment]
The tutorials are on http://azure.com - click on Documentation -> Web & Mobile -> Mobile Apps -> Getting Started.
