### ISSUE TITLE
package.json, plugin.xml point to the wrong github repo

### ISSUE THREAD

**Issue by Chuxel** [Azure/azure-mobile-apps-cordova-client#3]
The repository that shows up in npm for the plugin is the old Azure Mobile Services plugin rather than this repository.

**Comment by shrishrirang** [comment]
https://www.npmjs.com/package/cordova-plugin-ms-azure-mobile-apps beta4 fixes https://github.com/Azure/azure-mobile-apps-cordova-client/issues/3
