### ISSUE TITLE
Logout dose not work.

### ISSUE THREAD

**Issue by lggroapa** [Azure/azure-mobile-apps-cordova-client#30]
Calling logout does not clear cookies saved by the Cordova InAppBrowser, if I call logout then i call login again it will automatically login without allowing the user to enter his credentials. 

Is my assumption correct or am i doing something wrong?

**Comment by adrianhall** [comment]
Logout clears the token from the backend.  Unfortunately, social providers store a cookie as well, which causes them to remain logged in.  Although you have logged out of the "zumo" endpoint, you have not logged out of the social provider.  Unless we log **all** of your apps out, you won't get rid of the token from the social provider.  Unfortunately, this is a limitation of using social providers in Cordova.

**Comment by jsiegmund** [comment]
This behavior doesn't seem to be limited to only social providers. I see the same thing happening using Azure Authentication. I can imagine that's due to the same cause, but I was kind of expecting this to work. Either that or there should be a little more guidance on how to actually make sure your user is logged out completely.

**Comment by lggroapa** [comment]
I have a workaround for this. The credentials are actually stored in the InAppBrowses cache, all you need to do is add "**clearsessioncache=yes,clearcache=yes**" to the **window.open** that opens the URL to OAUTH providers, this will allow the user to enter new credentials.

**Comment by jsiegmund** [comment]
Cool, but workaround indeed. I'm working on a solution too, you can actually call the Azure AD endpoint to signout and it will clear the cookie for you as well. Will document in a blog post and post that here when done.

**Comment by lggroapa** [comment]
I am unaware of the Azure AD signout call. Looking forward to your blog post.

**Comment by jsiegmund** [comment]
See http://blog.repsaj.nl/index.php/2016/09/azure-logging-out-of-azure-ad-oauth/. There's actually two logout endpoints you should/can use: one of your web API and one of the oauth provider you're using (which can be Azure AD but can also be something else). Clearing the web api one is enough to log out and being able to log in as another user, it will not log out the user from the provider (so next time you select the same user, that will login without credentials depending on the provider settings and stored cookie).
