### ISSUE TITLE
WindowsAzure is not defined

### ISSUE THREAD

**Issue by J-Yen** [Azure/azure-mobile-apps-cordova-client#31]
Hi everyone,

I want to use Azure App Services with Ionic 2. I have installed the Cordova plugin with the folowing command: 
cordova plugin add cordova-plugin-ms-azure-mobile-apps

However, if i want to initiate an instance of WindowsAzure.MobileServiceClient it always throws an error: "WindowsAzure is not defined".

Data provider:
```
@Injectable() 
 export class Data {
  client: WindowsAzure.MobileServiceClient;
  todoItemTable: WindowsAzure.MobileServiceTable;

  getData():WindowsAzure.asyncPromise {
    if (!this.client) {
      this.client = new WindowsAzure.MobileServiceClient('https://url.azurewebsites.net');
    }
    this.todoItemTable = this.client.getTable("todoitem");
    return this.todoItemTable.read();
  }
```

home.ts:
```
constructor(public navCtrl: NavController,private platform:Platform, private dataService: Data) {
    this.platform.ready().then(()=> {
      this.dataService.getData();
    });
  }
```

**Comment by florianbepunkt** [comment]
Have you found a solution to this? I have the exact same problem.

**Comment by J-Yen** [comment]
It worked on a real device, but not in the browser. (Only Cordova supported devices)
