### ISSUE TITLE
Don't support baidu push

### ISSUE THREAD

**Issue by yaibait** [Azure/azure-mobile-apps-cordova-client#34]
Push.prototype.register only have wns, gcm or apns, I need to use what device platform when i register baidu 
I try this but not work 

`        baidu_push.startWork("BNafRPUIqamfe1mRxDXfYG09", function(data){
                console.log(data);
                var handle = data.appId;
                alert("baidu appId");
            client.push.register('gcm', handle, {
                  mytemplate: { body: { data: { message: "{$(messageParam)}" } } }
              });
        });
`

**Comment by adrianhall** [comment]
Baidu is not supported by Azure Notification Hubs.  Once Baidu is supported, the registration process (which wraps Notification Hubs registration process) will work as well.
