### ISSUE TITLE
Would be useful to be able to use a Bearer token from e.g. ADAL

### ISSUE THREAD

**Issue by bjartebore** [Azure/azure-mobile-apps-cordova-client#35]
It would be useful if we could switch the authentication implemented with ADAL. As I see it, the only thing needed here is a way of adding a Authorization Bearer token instead of the X-ZUMO-AUTH token that the SDK uses. This could be implemented as an alternative method to the client.login() e.g client.loginOauth(bearerToken).

**Comment by adrianhall** [comment]
To use the ADAL token, you "swap" the token with a ZUMO token.  This is documented as the "client flow".  My [blog](https://shellmonger.com/2016/04/06/30-days-of-zumo-v2-azure-mobile-apps-day-4-adal-integration/) has the details.

**Comment by adrianhall** [comment]
(PS - if the blog answers the question, please close this issue)

**Comment by adrianhall** [comment]
Closing issue as there is no response in over a week.
