### ISSUE TITLE
WindowsAzure is not defined

### ISSUE THREAD

**Issue by florianbepunkt** [Azure/azure-mobile-apps-cordova-client#36]
Hi, I want to use Azure with Ionic 2. I installed the Cordova plugin via `ionic plugin add cordova-plugin-ms-azure-mobile-apps`

But when I try to WindowsAzure.MobileServiceClient I get this error `"WindowsAzure is not defined"`

I saw another user described the exact same issue, however he closed his issue without posting the solution. Any help is appreciated.

**Comment by adrianhall** [comment]
You cannot access plugins (and hence the WindowsAzure object) until the device is ready.  The most common error is trying to access WindowsAzure before the deviceready is fired.

If this answers your question, please close the issue!

**Comment by florianbepunkt** [comment]
No, I called it in the constructor of app.components.ts inside a deviceready:

```
constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();

		console.log('check');

		this.client = new WindowsAzure.MobileServiceClient('https://bepunkttest.azurewebsites.net');

    });
  }
```

**Comment by adrianhall** [comment]
Ok.  I've not seen this before (I haven't used Ionic), so I'll check into it.

**Comment by shrishrirang** [comment]
Are you running your app in a browser? If yes, are you using `ionic run browser` or `ionic serve`? 

`ionic serve` does not load plugins, refer https://github.com/driftyco/ionic-cli/issues/354. 

Instead use:
```
ionic platform add browser
ionic run browser
```

`WindowsAzure` will be available in the _global namespace_ once the ready event (or equivalent) is fired:
```
$ionicPlatform.ready(function() { 
    var client = new WindowsAzure.MobileServiceClient('http://app-url');
}
```

Please close the issue if this helps. If not, please share your ionic version, platform you are running on and what command you are using to run your app.

**Comment by adrianhall** [comment]
Closing this issue now (it's been a week).  If you are still having problems, please re-open and provide the details that Shrirang asked for.
