### ISSUE TITLE
Issues getting Push's to work on app

### ISSUE THREAD

**Issue by kinoli** [Azure/azure-mobile-apps-cordova-client#37]
Hello, I can't seem to get this to work, I've spend several days, with no luck.

I did all of the certificates/provisioning as necessary, I added the p12 file to the sandbox location in the Azure portal, I then try to send a message and the app never receives it.

When I load up the app (on the device, from xcode run), all the console log's seem to indicate everything is setup properly.

I'm firing this code after onDeviceReady. Note: I have no idea if what I have for https://xxxxxxxxx.azurewebsites.net/ is correct. I'm really just guessing because I don't know where to get it from.

Please help.

        var push = PushNotification.init({
            "android": {
                "senderID": "SENDER-ID"
            },
            "ios": {"alert": "true", "badge": "true", "sound": "true"}, 
            "windows": {} 
        });
        var appUrl = 'https://xxxxxxxxx.azurewebsites.net/';
        var client = new WindowsAzure.MobileServiceClient(appUrl);

        // Handle the registration event.
        push.on('registration', function (data) {
            console.log('registration RECEIVED');
          // Get the handle returned during registration.
          var pushRegId = localStorage.pushDeviceId = data.registrationId;

          var name = 'gcm'; // For android - default
          if (device.platform.toLowerCase() === 'ios') {
              name = 'apns';
          }
          client.push.register(name, pushRegId, {
            mytemplate: { body: { aps: { alert: "{$(messageParam)}" } } }
          });

        push.on('notification', function(data) {
            console.log('PushPlugin RECEIVED', data);
            utils.doAlert('Push Received: ' + data.message);
        });

        push.on('error', function(e) {
            console.error('PushPlugin ERROR', e);
        });

**Comment by adrianhall** [comment]
I recommend following the tutorials rather than guessing.  The URL on azurewebsites.net is something that you have to create before you can do this.  Go back to the tutorials and complete them in order.

**Comment by kinoli** [comment]
The problem is, I don't need a backend. All I need to do is use Azure to send push notifications to my cordova mobile app.

**Comment by adrianhall** [comment]
Then don't use the Azure Mobile Apps Client SDK.  The Azure Mobile Apps Client SDK is for working with the Azure Mobile Apps backend.  Use Notification Hubs directly.

**Comment by kinoli** [comment]
Do you know if their is a tutorial for using just the Notification Hubs?

**Comment by adrianhall** [comment]
https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-push-notification-overview/
