### ISSUE TITLE
SignalR support

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-mobile-apps-cordova-client#4]
It would be nice to have SignalR support embedded in the library. WebAPI 2 already generates a JavaScript file for the proxy, so it should be relatively easy to just point to that endpoint, fetch the proxy and make sure the SignalR authentication is already dealt with using the bits and pieces available within the mobile apps client.

**Comment by adrianhall** [comment]
Hi @jsiegmund - can you please post this feature request in our UserVoice at http://feedback.azure.com - this would be long-range and would actually have impact across all the client platforms, so I want to get it stored in the right place.

**Comment by jsiegmund** [comment]
Sure, done! https://feedback.azure.com/forums/34192--general-feedback/suggestions/13123275-provide-signalr-support-for-azure-apps-cordova-cli
