### ISSUE TITLE
The latest version should be RC1 instead of beta 6.

### ISSUE THREAD

**Issue by Paul-Lo** [Azure/azure-mobile-apps-cordova-client#40]
Could someone help update this Cordova Azure Mobile App plugin from **beta 6** into **v2.0.0-rc1-41020.190139** which is from https://github.com/Azure/azure-mobile-apps-js-client?

**Comment by adrianhall** [comment]
I'm not sure I understand the question.  The current released version is 2.0.0-rc1 - what problem are you exactly having?

**Comment by shrishrirang** [comment]
@Paul-Lo, are you referring to the header in https://github.com/Azure/azure-mobile-apps-cordova-client/blob/master/www/MobileServices.Cordova.js which says beta6? Don't read too much into it.

The version in package.json and plugin.xml are the ones that determine the Cordova plugin version and both are rc1.

The beta6 version header in https://github.com/Azure/azure-mobile-apps-cordova-client/blob/master/www/MobileServices.Cordova.js just means that the file was built during the beta6 timeframe of http://github.com/azure/azure-mobile-apps-js-client. The Javascript and Cordova SDK repositories don't quite operate in lock step. This means every time we do a Javascript release, we don't necessarily do a Cordova release (and vice versa) and that is the reason the header says beta6.

**Comment by Paul-Lo** [comment]
This resolved my question. 
Thanks a lot for your explanation, Shrirang!
