### ISSUE TITLE
Error push.gcm.registerNative

### ISSUE THREAD

**Issue by yaibait** [Azure/azure-mobile-apps-cordova-client#45]
Hi 
I try to register device for push notification : 

push.on('registration', (data) => {
        console.log("device token ->", data.registrationId);
        //TODO - send device token to server
        var handle = data.registrationId;
        console.log("client",client.push);
client.push.gcm.registerNative(handle).then(function(data){
                alert("success");
            },function(error){
                alert(error);
                console.log(error);
          });

      });

But i get error : 
Failed to load resource: the server responded with a status of 404 (Not Found) 
http://xxxxx.azurewebsites.net/push/registrations?platform=gcm&d…c_xKbaFUy8ydAsInGIILF6iP-egXoItelHrORhrOjHh8QFkJowQfcat6k_wEVVmiVMvnGXp0_x

**Comment by adrianhall** [comment]
Just to follow up - this is indicative that the push endpoint is not configured through the Push option on the Azure Portal in your App Service.
