### ISSUE TITLE
PhoneGap Build failing with SQLLite issue

### ISSUE THREAD

**Issue by emtopping** [Azure/azure-mobile-apps-cordova-client#46]
Hi, try to build on PhoneGap and it's failing with:
Installing "cordova-plugin-ms-azure-mobile-apps" at "2.0.0" for android
Dependent plugin "cordova-plugin-inappbrowser" already installed on android.
Fetching plugin "cordova-sqlite-storage@1.4.8" via npm
Installing "cordova-sqlite-storage" at "1.4.8" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-sqlite-storage':CordovaError: Uh oh!
"/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/libs/sqlite-connector.jar" not found!
    at copyFile (/project/cordova/lib/pluginHandlers.js:202:36)
    at copyNewFile (/project/cordova/lib/pluginHandlers.js:234:5)
    at install (/project/cordova/lib/pluginHandlers.js:37:17)
    at Object.process (/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/project/cordova/Api.js:198:10)
    at handleInstall (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:611:6)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:414:24
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
Failed to install 'cordova-plugin-ms-azure-mobile-apps':CordovaError: Uh oh!
"/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/libs/sqlite-connector.jar" not found!
    at copyFile (/project/cordova/lib/pluginHandlers.js:202:36)
    at copyNewFile (/project/cordova/lib/pluginHandlers.js:234:5)
    at install (/project/cordova/lib/pluginHandlers.js:37:17)
    at Object.process (/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/project/cordova/Api.js:198:10)
    at handleInstall (/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:611:6)
    at /.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:414:24
    at _fulfilled (/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
Uh oh!
"/project/cordova/plugins/cordova-sqlite-storage/node_modules/cordova-sqlite-storage-dependencies/libs/sqlite-connector.jar" not found!

**Comment by adrianhall** [comment]
Can you install cordova-sqlite-storage into your project separately?  If you can't, I think you need to go check in with them.

**Comment by emtopping** [comment]
@adrianhall Hi, Adrian, no I can't! I've posted on the PGB forum. Thanks.

**Comment by emtopping** [comment]
This comment seems to indicate that the cordova-sqlite-storage plugin is not supported on PhoneGap CLI on PhoneGap Build. Can you remove the dependency?
https://github.com/litehelpers/Cordova-sqlite-storage/issues/588#issuecomment-262173109

**Comment by adrianhall** [comment]
Unfortunately, we cannot.  We do not technically support PhoneGap - we are explicit in our support for Cordova, and specific Cordova releases.  I'm sorry this won't work for you.

**Comment by emtopping** [comment]
I've no idea why you decided to add such a dependency, Adrian. I was an early adopter of Azure Mobile Services and it appears to have gone backwards. Is there any early version that doesn't use it. Very sad & disappointed.

**Comment by adrianhall** [comment]
We include such a dependency because a major part of the functionality is the offline sync capabilities.  You can go back to one of the earliest releases to get a release that doesn't use SQLite (and hence has no offline sync capabilities).  You can also use raw HTTPS calls to the OData endpoints to get similar functionality.

**Comment by emtopping** [comment]
Care to specify a version to aid me, please? I understand why you've added the functionality but not how you have implemented it. Perhaps you could branch the dependent plugin...

**Comment by adrianhall** [comment]
If you don't need the SQLite functionality, just include the JS Client (rather than the plugin) - it doesn't have the dependency and can be added via the CDN download and/or NPM package for inclusion.

**Comment by emtopping** [comment]
Apologies for the late reply, Adrian. The JS client sounds ideal. Many thanks & I'm sorry for growling. Having a Tesco self-checkout moment!
I personally believe the Azure clients should be as lightweight as possible and allow developers to cosider their own use cases for off-line persistence/retry scenarios.
Thanks,

Martin

**Comment by brgopalakrishnan** [comment]
Martin, Please let me know did the JS Client resolved the issue? I am working to resolve the same issue. Thanks

**Comment by emtopping** [comment]
It did, Babu.

**Comment by brgopalakrishnan** [comment]
Thank you Martin. I assume you downloaded the .js file (MobileServices.Cordova.js) and added the same to phonegap client.

**Comment by emtopping** [comment]
Yes, as far as I recall ,Babu. I am on holiday at the moment, without a
computer,, but the pure js solution worked for a realtime approach ,
without the offline support. I even implemented in on arduino using simple
Http posts with appropriate headers.



On 9 Sep 2017 04:01, "Babu R Gopalakrishnan" <notifications@github.com>
wrote:

Thank you Martin. I assume you downloaded the .js file
(MobileServices.Cordova.js) and added the same to phonegap client.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-mobile-apps-cordova-client/issues/46#issuecomment-328247562>,
or mute the thread

**Comment by brgopalakrishnan** [comment]
No Worries. Will give a shot. Enjoy. Will get back to you if I go thru any hiccups.

**Comment by brgopalakrishnan** [comment]
Yep, it works ;-). Thanks

**Comment by emtopping** [comment]
Great! :-)
