### ISSUE TITLE
Content Security Policy errors in Ionic v3 project

### ISSUE THREAD

**Issue by jrmcdona** [Azure/azure-mobile-apps-cordova-client#49]
Hi-Is this necessary in an Ionic project?  

When I add this in I get a lot of errors in the browser logs.

```
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net; style-src 'self'; media-src *">
```

polyfills.js:3 Unhandled Promise rejection: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net".
 ; Zone: <root> ; Task: Promise.then ; Value: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net".

**Refused to load the font 'http://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff2' because it violates the following Content Security Policy directive: "default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

index.html:1 Refused to load the font 'http://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.woff' because it violates the following Content Security Policy directive: "default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

index.html:1 Refused to load the font 'http://c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.ttf' because it violates the following Content Security Policy directive: "default-src 'self'
      data: gap: https://login.live.com https://ambassadors-mobile-dev.azurewebsites.net". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by jrmcdona** [comment]
Didn't have the right settings.  Got it working.

**Comment by jrmcdona** [comment]
Actually I am still getting these.   Now the frame is getting block.  I believe this must be the frame for the auth form.

I am currently running the project like this:
ionic cordova run browser
Do you know what I should set the frame-src or child-src CSP to, to avoid this?

`Refused to frame 'data:text/html,%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3Cmeta%20name%3D'v…uth%2Flogin%2Fmicrosoftaccount%253Fsession_mode%253Dtoken')%3C%2Fscript%3E' because it violates the following Content Security Policy directive: "child-src 'self'". Note that 'frame-src' was not explicitly set, so 'child-src' is used as a fallback.`

**Comment by elamalani** [comment]
@jrmcdona Sorry for following up late on this issue? Any update on this one? Do you still see the issues?

**Comment by elamalani** [comment]
Closing this issue as we haven't heard back from you. Feel free to contact us if you have any questions.

**Comment by bmourat** [comment]
Hi @erperejildo,
Could you please provide you `Content-Security-Policy` value and full error that you receive.

**Comment by erperejildo** [comment]
> content.js:1 Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('SOME_CODE'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by erperejildo** [comment]
this is the `head` of my default `index.html`:
   ```
<meta charset="utf-8">
    <title>Ionic App</title>

    <base href="/" />

 <meta name="viewport" content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">

    <link rel="icon" type="image/png" href="assets/icon/favicon.png">

    <!-- add to homescreen for ios -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
```

What else do I need to add?

**Comment by bmourat** [comment]
Try adding this:

```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com https://your-app-name.azurewebsites.net; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *">
```

Replace `your-app-name` with your azure app name.

**Comment by erperejildo** [comment]
still the same. Moving now to `Ionic 3` to avoid some other random issues.

Thanks for helping anyway

**Comment by bmourat** [comment]
Hi @erperejildo 
Did you resolve your issue when moved to `Ionic 3`?

**Comment by erperejildo** [comment]
@bmourat yes I did. I'll wait for a proper release now
