### ISSUE TITLE
Push registration with tags not working

### ISSUE THREAD

**Issue by atsats** [Azure/azure-mobile-apps-cordova-client#5]
I'm using the latest beta of the Cordova plugin for Azure mobile apps that's here.

This plugin currently does not appear to support push registration with tags. Specifically, the plugin method: Push.prototype.register() does not take a tags parameter.

So, I patched this method to supply tags for the push notification registration, and I can see the tags parameter being packaged in the PUT REST API request to Azure - But, the tags I supply are still not registered.

I'd like to know if anyone has solved this issue of push notification registration with tags using this plugin or if anyone can add some insight as to why the PUT API REST call would not add the tags. Here's the request content sent to Azure in the PUT request call. Note that the registration does succeed, but the tags are not added.

`{
	"tags":["test:1","hello"],
	"installationId":"efa788c5-e494-a6d4-02c3-...",
	"pushChannel":"c1mn7MzRAqo:APA91b...",
	"platform":"gcm",
	"templates":{},
	"secondaryTiles":{}
}`

**Comment by adrianhall** [comment]
You cannot register for tags within the client (due to security).  Instead, create a custom API for registration and register for tags there.

**Comment by jsiegmund** [comment]
For anyone else who ends up here wondering "ok, so how do I do that?", I've posted a blog with the answer (or at least something that works) here: http://blog.repsaj.nl/index.php/2016/08/azure-custom-function-bindings-notification-tags-in-cordova-apps/
