### ISSUE TITLE
cordova-plugin-ms-azure-mobile-apps plugin does not install on Cordova 7/8

### ISSUE THREAD

**Issue by DoctorDubb** [Azure/azure-mobile-apps-cordova-client#52]
Trying to install 'cordova plugin add cordova-plugin-ms-azure-mobile-apps' on:
```
cordova -v
8.0.0
npm -v
5.6.0
```
I get the following error:
"Failed to install 'cordova-plugin-ms-azure-mobile-apps': Error: ENOENT: no such file or directory, open 'xxx\platforms\android\AndroidManifest.xml'"

Refer to: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html for breaking changes with Cordova 7 and AndroidManifest.xml i.e.
```
<!-- An existing config.xml -->
<edit-config file="AndroidManifest.xml" target="/manifest/application" mode="merge">
<!-- needs to change to -->
<edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
```

Any possibility that this could be resolved as i have other dependencies that require the later version on Cordova?

**Comment by ChanchaiKunnasut** [comment]
+1 i have the same problem.

**Comment by dmagadi** [comment]
+1 I have the same issue

**Comment by bmourat** [comment]
@DoctorDubb thanks for reporting this.
The main reason for this is that one of the dependencies doesn't support cordova-android platform v7.0. I've created PR for this #53.

**Comment by DoctorDubb** [comment]
@bmourat Thanks for that - keep us up to date how it goes

**Comment by lgadola** [comment]
same issue

**Comment by henriqueadonai** [comment]
same!

**Comment by Prasoon1983** [comment]
same here :(

**Comment by mbeckenbach** [comment]
Whats the status with this? The PR is already a month ago.

**Comment by elamalani** [comment]
Hi everyone, sorry for the delayed response on this thread. We have the fix ready in a PR and will release Cordova SDK soon. I'll keep this thread posted once the SDK is released. 

Thanks!

**Comment by profgoetze** [comment]
Any news on this issue?

**Comment by elamalani** [comment]
@profgoetze This SDK release is still in our backlog. Please give us a week or two to release it.

**Comment by simya846** [comment]
Any update?

**Comment by elamalani** [comment]
@simya846 We are in the process of releasing. I will keep this thread posted once we release the SDK.

**Comment by simya846** [comment]
Thank you :)

**Comment by elamalani** [comment]
@simya846 @profgoetze @mbeckenbach We have just released the latest Cordova plugin for Azure Mobile Apps which works on Cordova 7/8. Please give it a try. I'm closing this issue now.

https://github.com/Azure/azure-mobile-apps-cordova-client/releases
