### ISSUE TITLE
Android build error in VS 2017 with 2.0.1.

### ISSUE THREAD

**Issue by gmigueis** [Azure/azure-mobile-apps-cordova-client#60]
Android build fails on Visual Studio 2017 with version 2.0.1 of the plugin: Module 'com.microsoft.azure:azure-mobile-android:3.3.0' depends on one or more Android Libraries but is a jar.

Downgrading to version 2.0.0 solves the issue.

**Comment by dhei** [comment]
We merged #59 and released v2.0.2 today. This issue should be resolved and can be closed.
