### ISSUE TITLE
Could not authenticate with google provider

### ISSUE THREAD

**Issue by kkaczmarzyk** [Azure/azure-mobile-apps-cordova-client#62]
I'm getting this error:
"Error: Could not authenticate with google provider.
Could not read redirect uri scheme from manifest. Did you have this line '<meta-data android:name=".azure_mobileapps_redirect_uri_scheme" android:value="YOUR_URI_SCHEME"/>' appeared and configured in your AndroidManifest.xml?"
I am not exactly sure what does it mean. What is wrong in my project if I'm getting this error? What is redirect uri scheme?

**Comment by bmourat** [comment]
Hey @kkaczmarzyk,
Did you resolve your issue?

**Comment by kkaczmarzyk** [comment]
I didn't. I used just FCM.

**Comment by bmourat** [comment]
I'll close this issue for now. If you'll have any other questions, please feel free to ask.
