### ISSUE TITLE
SyncContext.pull performance

### ISSUE THREAD

**Issue by daviddickson** [Azure/azure-mobile-apps-cordova-client#66]
I'm not sure if this is the right place to post this so if it isn't I apologize. I'm trying to sync an Azure database to a hybrid app built using the Ionic platform. If I use the SyncContext.pull method on the largest table which contains ~170k records it takes roughly 6 hours to complete the pull and insertion into the local db. Does this sound like expected behavior? I did not see anything in the documentation about expected performance.

**Comment by daviddickson** [comment]
I've already increased the page size. I should have said that originally.

**Comment by daviddickson** [comment]
I agree that transferring a large dataset over the wire is not an ideal approach, but offline functionality is a priority and a large initial transfer is the approach being taken currently.  Since the initial pull is slow, I am grabbing the data from the table endpoints in chunks and then inserting into the local database. I am using the incremental sync as described in the documentation for the subsequent pulls but I am still experiencing performance issues.

**Comment by jaelim-ms** [comment]
The initial database sync with large amount of data definitely impacts performance and it is a **known limitation** of Azure Mobile Apps. I apologize for any inconvenience.

**Comment by jaelim-ms** [comment]
@daviddickson Do you have anything else that I can assist you?
