### ISSUE TITLE
custom authentication and sync'ing tables

### ISSUE THREAD

**Issue by medida** [Azure/azure-mobile-apps-cordova-client#67]
Hello
I'm building an ionic 3/ angular  mobile app and I'm implementing a custom authentication process as the project historically uses an internal one.

I have the authentication process setup on the .net backend and i'm returning a token / user details

the tablecontroller has [Authorize] on the GET  - but i can see that the X-ZUMO-AUTH is not present in the headers when i request the .PULL to GET the data - thus its failing with a 401.

Without the [Authorize] it works fine.

Here's some of my code...

Meta tag on the index.html file
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://10.0.2.2:44322; style-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval; https://10.0.2.2:44322';">

At present i'm testing locally in visual studio and on an android emulator ( with livereload)
`    client = new WindowsAzure.MobileServiceClient("https://10.0.2.2:44322"); 
`

I'm calling the login process - the auth redirects to my own LOGIN API along with the username / password - this then returns a TOKEN which i can see gets stored int he client.currentUser OK
`
client.login("auth", {username:"hello" , password:"world"}).done((val) => {
      console.log(client);
    
      this.initializeStore()

});
`
When i try and get new data... the token is not been sent????

Any help would be great - I not found any solution which works at the moment.

**Comment by bmourat** [comment]
Hi @medida 
How did you setup your authentication process on the backend? Did you follow some tutorial?

**Comment by medida** [comment]
I followed a selection of pages i found

https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#custom-auth

https://www.newventuresoftware.com/blog/custom-authentication-with-azure-mobile-apps



RUN visual studio as an administrator - its the only way HTTPS will work - especially if testing locally and the login process calls https of the URL.

In the .net backend you need to return the authentication JSON like :  This is Case sensitive.

authenticationToken = token.RawData,
user =  new {userid = username }


In my web.config i needed to specify the correct <appSettings>

<add key="SigningKey" value="MY KEY GOES HERE" /> -- this key needs to match the one which is used to generate the token!
<add key="ValidAudience" value="https://10.0.2.2:44322/" /> -- my URL as i'm calling if from an emulator this resolves to localhost on my PC
<add key="ValidIssuer" value="https://10.0.2.2:44322/" />


My ionic app  - i call the login process like

 client.login("auth", {username:"hello" , password:"world"}).done((val) => {
      console.log(client);
      this.initializeStore(); // call to pull data
      });

  }


Any more questions let me know.

**Comment by bmourat** [comment]
And how did you setup route to your custom auth controller?

**Comment by medida** [comment]
Hi

so the 'auth' bit in **client.login("auth", {username:"hello"** 
actually redirects to 'myURL/.auth/login/auth' - i just added a mapHttpRoute to my startup.mobileApp.cs file like:

 config.Routes.MapHttpRoute("Auth", ".auth/login/auth", new { controller = "Auth" });

this then redirect all traffic from .auth/login/auth  to my new controller

this is a copy of my Authcontroller for you - at the moment its very basic, but does the job for initall testing.

`
using Microsoft.Azure.Mobile.Server.Config;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using System.Web.Http;
using Microsoft.Azure.Mobile.Server.Login;
using Newtonsoft.Json.Linq;

namespace MyAppService.Controllers
{
    //[MobileAppController]
    public class AuthController : ApiController
    {


        //https://adrianhall.gitlab.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/
        // outlines the format of the JSON back to the client device

        [HttpPost]
        public HttpResponseMessage Post(JObject Val) //(string username, string password)
        {

            string username = Val["username"].ToString();
                string password = Val["password"].ToString();
            // return error if password is not correct
            if (!this.IsPasswordValid(username, password))
            {
                return this.Request.CreateUnauthorizedResponse();
            }

            JwtSecurityToken token = this.GetAuthenticationTokenForUser(username);

            return this.Request.CreateResponse(HttpStatusCode.OK, new
            {
                authenticationToken = token.RawData,
                user =  new {userid = username }
            });
        }

        private bool IsPasswordValid(string username, string password)
        {
            // this is where we would do checks agains a database

            return true;
        }

        private JwtSecurityToken GetAuthenticationTokenForUser(string username)
        {
            var claims = new Claim[]
            {
        new Claim(JwtRegisteredClaimNames.Sub, username)
            };

            var signingKey = Environment.GetEnvironmentVariable("WEBSITE_AUTH_SIGNING_KEY");
            var audience = "https://10.0.2.2:44322/"; // audience must match the url of the site
             var issuer = "https://10.0.2.2:44322/"; // audience must match the url of the site

           
    JwtSecurityToken token = AppServiceLoginHandler.CreateToken(
        claims,
        signingKey,
        audience,
        issuer,
        TimeSpan.FromHours(24)
        );

            return token;
        }
    }
}
`



One extra thing - as i was testing with ionic livereload i found i had to add CORS
 
so added: **using System.Web.Http.Cors;**

I then added this to the startup.mobileapp.cs file 
'
HttpConfiguration config = new HttpConfiguration();
 var cors = new EnableCorsAttribute("*", "*", "*");
config.EnableCors(cors);
'

**Comment by bmourat** [comment]
Hi @medida. Thanks for the info. Actually, I did the same with the route registration. But I'm getting `bad request` when trying to authenticate the user with Cordova. Did you receive such error during setup of your app?

**Comment by clpolet** [comment]
@medida Are you still facing this issue?

**Comment by medida** [comment]
Hi. 
I have got the authentication working but as i have moved on i have discovered other issues with sync'ing tables where the data is coming from a complex SQL procedure.... Its possible, but i'm trying different solutions to get it the most elegant.
