### ISSUE TITLE
Changes in Azure App Authentification - Implications

### ISSUE THREAD

**Issue by thomasarnoldvs** [Azure/azure-mobile-apps-cordova-client#69]
Dear Contributor, Dear Project Members

I read that there will be a lot of changes in the Azure App Authentication section.

e.g. The login via a Microsoft Login will be deactivated: [https://apps.dev.microsoft.com](url)

> We will no longer support registering and managing converged and Azure AD applications here starting May 2019. We recommend that you manage your existing applications and register new applications by using the App registrations (now Generally Available) experience in the Azure portal. Click this banner to launch the new and improved experience. 

There will be also a new JS Library for MSAL [https://developer.microsoft.com/en-us/identity/blogs/msal-net-is-now-generally-available/](url)

Does anyone have any idea what this means for this Cordova project?

Thank you for your time.

Kind Regards,

Thomas arnold

**Comment by elamalani** [comment]
@thomasarnoldvs The old https://apps.dev.microsoft.com site is being decommissioned. App registrations will be handled through the Azure Portal instead. You can still use your account to login to Azure portal.

We are going to make no changes in the Authentication service. Please refer to the Readme section that describes the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-cordova-client#future-of-azure-mobile-apps).
