### ISSUE TITLE
Rename to Mobile Apps

### ISSUE THREAD

**Issue by jsiegmund** [Azure/azure-mobile-apps-cordova-client#8]
Although the repo is called azure-mobile-apps-cordova-client, we're still using WindowsAzure.MobileServiceClient in our code. Since Azure Mobile Services are being replaced by mobile apps, it would make more sense to rename the client object to WindowsAzure.MobileAppsClient.

**Comment by adrianhall** [comment]
Thanks for the input.  We are not going to be changing the name of the client - it is embedded across our client SDK, documentation and in multiple other resources (including videos, blogs, etc.).  This would be a major shift in the naming schema that we are not going to work on.
